name: waka
description: Waka property management system application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http : 
  form_validator: ^0.1.7
  shared_preferences: ^0.5.12+4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
font_awesome_flutter:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/all_balances.png
    - assets/images/having_balance.png
    - assets/images/occupied_rooms.png
    - assets/images/payments.png
    - assets/images/rent_collected.png
    - assets/images/tenants.png
    - assets/images/units.png
    - assets/images/vaccant_rooms.png
    - assets/images/waka_logo.png
    - assets/images/waka_logo_header.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


